apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mediinfo-lyra-pingtai-cunchu
    version: 1.1.78
  name: mediinfo-lyra-pingtai-cunchu-1.1.78
  namespace: mcrp-production
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mediinfo-lyra-pingtai-cunchu
      version: 1.1.78
  template:
    metadata:
      annotations:
        dapr.io/app-id: mediinfo-lyra-pingtai-cunchu
        dapr.io/app-port: "80"
        dapr.io/enabled: "true"
        dapr.io/http-max-request-size: "1000"
      creationTimestamp: null
      labels:
        app: mediinfo-lyra-pingtai-cunchu
        version: 1.1.78
    spec:
      containers:
      - image: 172.19.30.186:8000/mcrp/release-20211205/mediinfo-lyra-pingtai-cunchu:d5827b4-stable
        imagePullPolicy: IfNotPresent
        name: mediinfo-lyra-pingtai-cunchu
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts: 
          - name: mediinfo-lyra-pingtai-cunchu-volume
            mountPath: "/app/upload"
      restartPolicy: Always
      volumes: 
      - name: mediinfo-lyra-pingtai-cunchu-volume
        persistentVolumeClaim:
          claimName: mediinfo-lyra-pingtai-cunchu-claim
