apiVersion: v1
kind: Service
metadata:
  labels:
    app: mediinfo-lyra-pingtai-cunchu
  name: mediinfo-lyra-pingtai-cunchu
spec:
  ports:
  - name: mediinfo-lyra-pingtai-cunchu
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: mediinfo-lyra-pingtai-cunchu
  type: NodePort
status:
  loadBalancer: {}
